"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
console_title_template = "{{ .Folder }}"
version = 2

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

  [[blocks.segments]]
  foreground = "#BBC4B9"
  leading_diamond = "<#BFA8BF>~</> "
  style = "diamond"
  template = "{{ .UserName }} "
  type = "session"

    [blocks.segments.properties]
    display_host = true

  [[blocks.segments]]
  foreground = "#BFA8BF"
  style = "diamond"
  template = "<#fff>{{ .UpstreamIcon }}</>{{ .HEAD }}"
  type = "git"

    [blocks.segments.properties]
    branch_icon = " "
    fetch_stash_count = true
    fetch_status = true
    fetch_upstream_icon = true
    fetch_worktree_count = true

  [[blocks.segments]]
  foreground = "#BFA8BF"
  style = "powerline"
  template = " <#fff></> {{ .Name }} "
  type = "shell"

[[blocks]]
alignment = "right"
type = "prompt"

  [[blocks.segments]]
  foreground = "#fff"
  style = "plain"
  type = "text"

  [[blocks.segments]]
  foreground = "#fff"
  style = "diamond"
  template = " <#BBC4B9>{{ .FormattedMs }}s</> <#fff>󰇝</>"
  type = "executiontime"

    [blocks.segments.properties]
    style = "dallas"
    threshold = 0

  [[blocks.segments]]
  foreground = "#BBC4B9"
  style = "diamond"
  template = " {{ .CurrentDate | date .Format }} "
  type = "time"

    [blocks.segments.properties]
    time_format = "Monday <#fff>at</> 3:04 PM"

  [[blocks.segments]]
  style = "diamond"
  template = " "
  type = "root"

    [blocks.segments.properties]
    root_icon = " "

  [[blocks.segments]]
  foreground = "#BBC4B9"
  style = "diamond"
  template = " <#fff></> {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} "
  type = "node"

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

  [[blocks.segments]]
  foreground = "#B6D6F2"
  leading_diamond = "<#BFA8BF>~</>"
  style = "diamond"
  template = "  {{ .Path }}"
  trailing_diamond = ""
  type = "path"

    [blocks.segments.properties]
    folder_icon = "/"
    folder_separator_icon = " / "
    home_icon = "home"
    style = "agnoster_full"

  [[blocks.segments]]
  foreground = "#BFA8BF"
  foreground_templates = [ "{{ if gt .Code 0 }}#fff{{ end }}" ]
  style = "plain"
  template = " ~ "
  type = "status"

    [blocks.segments.properties]
    always_enabled = true

[transient_prompt]
background = "transparent"
foreground = "#FEF5ED"
template = " "

